### ISSUE TITLE
Merge PR #22

### ISSUE THREAD

**Issue by zoeleu** [AtiLion/BotNeck-Bot#23]

**Comment by ari-rocha** [comment]
yes

**Comment by AtiLion** [comment]
The biggest issue with adding the documentation to the bot file itself is that you can't really reference the JS file in the modules. Meaning even if added, it still won't be visible when developing, hence why my idea was to add it to the Wiki or a separate file in the repo.

Also I really haven't gotten the time to check over the code as a lot of it has been changed due to the formatting difference.

**Comment by AtiLion** [comment]
PR was closed due to the type of API provided not being visible or easily accessible to the developers. More details here: https://github.com/AtiLion/BotNeck-Bot/pull/22
